### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by CentofantiEze** [CosmoStat/wf-psf#103]
I encountered the following error while trying to run Wavediff (develop branch) on Jean Zay:

```
Traceback (most recent call last):
  File "/linkhome/rech/genaim01/uds36vp/.local/bin/wavediff", line 5, in <module>
    from wf_psf.run import mainMethod
  File "/gpfsdswork/projects/rech/ynx/uds36vp/repos/wf-psf/src/wf_psf/run.py", line 14, in <module>
    from wf_psf.utils.configs_handler import get_run_config
  File "/gpfsdswork/projects/rech/ynx/uds36vp/repos/wf-psf/src/wf_psf/utils/configs_handler.py", line 15, in <module>
    from wf_psf.plotting.plots_interface import plot_metrics
  File "/gpfsdswork/projects/rech/ynx/uds36vp/repos/wf-psf/src/wf_psf/plotting/plots_interface.py", line 14, in <module>
    import seaborn as sns
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/seaborn/rcmod.py", line 5, in <module>
    from . import palettes
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/seaborn/palettes.py", line 9, in <module>
    from .utils import desaturate, get_color_cycle
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/seaborn/utils.py", line 11, in <module>
    import pandas as pd
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/pandas/__init__.py", line 48, in <module>
    from pandas.core.api import (
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 76, in <module>
    from pandas.core.frame import DataFrame
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/pandas/core/frame.py", line 171, in <module>
    from pandas.core.generic import NDFrame
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/pandas/core/generic.py", line 169, in <module>
    from pandas.core.window import (
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/pandas/core/window/ewm.py", line 15, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /gpfslocalsup/pub/anaconda-py3/2022.05/envs/tensorflow-gpu-2.11.0+py3.10.8/lib/python3.10/site-packages/pandas/_libs/window/aggregations.cpython-310-x86_64-linux-gnu.so)
```

The content of the config file is the following:
```
---
  training_conf: training_config.yaml
```
On the training_config.yaml I have set a 2 cycles optimisation with 2 epochs per cycle both for the parametric and non-parametric models.

The Tensorflow module used on JeanZay is: tensorflow-gpu/py3/2.11.0. I am running the latest version of WaveDiff (WF-PSF v2.0.0) on the develop branch.

**Comment by CentofantiEze** [comment]
The bug was solved by uninstalling and re-installing the latest version of the pandas package (2.1.4). 

The `pandas` package is not a dependency of WaveDiff, however it is called by the `seaborn` package which is currently a WaveDiff requirement.

**Comment by jeipollack** [comment]
@CentofantiEze you wrote tensorflow version `2.9.1` but in your traceback log it states `tensorflow-2.11.0`

**Comment by CentofantiEze** [comment]
Oh sorry, I edited the comment.
