### ISSUE TITLE
Main Branch: KeyError: 'sed_sigma'

### ISSUE THREAD

**Issue by jeipollack** [CosmoStat/wf-psf#40]
Hi, 
  I attempted to run the `main` branch wf-psf code on the Apple M1 chip and encountered the `KeyError: 'sed_sigma'`.  Below is the traceback.
I do not encounter this error when running the `feature-multi-cycle` branch on the M1 chip, which seems to run to completion without any errors.
Comparing the two branches, i.e.  `main` and `feature-multi-cycle`, I see this keyword does not exist in the feature branch. 
But, this feature branch is several commits behind `main` so I am not sure whether this `sed_sigma` keyword should  exist.
  
`
Traceback (most recent call last):
  File "/Users/jenniferpollack/Projects/wf-psf/long-runs/train_eval_plot_script_click.py", line 376, in <module>
    main()
  File "/Users/jenniferpollack/miniconda/envs/wf-psf/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jenniferpollack/miniconda/envs/wf-psf/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jenniferpollack/miniconda/envs/wf-psf/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jenniferpollack/miniconda/envs/wf-psf/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jenniferpollack/Projects/wf-psf/long-runs/train_eval_plot_script_click.py", line 365, in main
    wf.script_utils.train_model(**args)
  File "/Users/jenniferpollack/miniconda/envs/wf-psf/lib/python3.9/site-packages/wf_psf/script_utils.py", line 125, in train_model
    SED_sigma=args['sed_sigma']
KeyError: 'sed_sigma'`

**Comment by jeipollack** [comment]
I do see that the SED_sigma param is listed in the [Readme](https://github.com/CosmoStat/wf-psf/tree/main/long-runs#wavediff-new-features) as a new feature.

**Comment by jeipollack** [comment]
I get the same error for the `feature-interp` branch which was one the latest PRs to `main` 

`Flow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Traceback (most recent call last):
  File "/Users/jenniferpollack/Projects/wf-psf/long-runs/train_eval_plot_script_click.py", line 376, in <module>
    main()
  File "/Users/jenniferpollack/miniconda/envs/wf-psf/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jenniferpollack/miniconda/envs/wf-psf/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jenniferpollack/miniconda/envs/wf-psf/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jenniferpollack/miniconda/envs/wf-psf/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jenniferpollack/Projects/wf-psf/long-runs/train_eval_plot_script_click.py", line 365, in main
    wf.script_utils.train_model(**args)
  File "/Users/jenniferpollack/miniconda/envs/wf-psf/lib/python3.9/site-packages/wf_psf/script_utils.py", line 125, in train_model
    SED_sigma=args['sed_sigma']
KeyError: 'sed_sigma'`

**Comment by jeipollack** [comment]
I added the missing `sed_sigma` arg to the `train_eval_plot_script_click.py` module.  But, encountered further arg type errors for params such as `-l_rate_param` and others.  So, I dug a bit through the commit history and found the previous working commands.
I opened a `bug fix` branch off of the `main` branch and added the previous working args. Now the code is running.  I will wait until the end before I submit a PR.

**Comment by tobias-liaudat** [comment]
Hi @jeipollack 
Sorry for the late reply; I'm slowly rebooting after the holidays.

It seems that some of the arguments were not properly added when we integrated the last developments of the code :/ If some of the arguments are missing, they should be added to the click scripts `train_eval_...`

If there are other issues, don't hesitate to comment on them
